### ISSUE TITLE
support for names at axis

### ISSUE THREAD

**Issue by WillyWinkel** [thillux/rPlots#1]
Hi,

I tried to make plots with the `plotWithConfidence` function and put strings on the axis instead of numbers.
My idea was to call `plotWithConfidence(a, y, abs(y/10.0), pdfFile="conf.pdf")` with 
`x <- c("bier", "mate", "water", "Weizen")` and
`y <- rnorm(length(x))`.
at the moment the script throws

```
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator
Calls: doConfidence -> plotWithConfidence -> diff -> diff.default
Execution halted
```

Would be awesome dude ;)

**Comment by thillux** [comment]
I added support for this in commit d7295a9eb6cc7aaeadae62d5f1e536af257c7c40.

**Comment by WillyWinkel** [comment]
perfect, thx a lot
