### ISSUE TITLE
show 0 line in plots

### ISSUE THREAD

**Issue by WillyWinkel** [thillux/rPlots#3]
Maybe thats an enhancement, but having the zero line in the plots would be great for overview sometimes. I've nearly done it by setting `yLim <- range(c(0,yData-e)) + c(0, deltaY)` in `plotWithConfidence`, but now high value seem to disappear.

example input save as "file":

```
50 0.101109457672 0.0344515183477
100 0.0952124669312 0.0235779036365
250 0.0955709876543 0.0193970525015
500 0.0953637566138 0.0167084040868
750 0.091978505291 0.0148734158778
1000 0.0910726629826 0.0134852754956
```

example code to execute:

```
#!/usr/bin/Rscript
# arg1 = input, arg2 = output, arg3 = xTitle, arg4 = yTitle
# input format:
# name average confidence

source("plot.r")
args<-commandArgs(TRUE)

doConfidenceCategorialFromFile <- function(name) {
    a <- read.table(name)
    plotWithConfidence(t(a[1]), t(a[2]), t(a[3]), pdfFile=args[2], xDataIsCategorial=TRUE, xTitle=args[3], yTitle=args[4])
}
doConfidenceCategorialFromFile(args[1])
```

call:
`Rscript confidence.r file file-confidence.pdf "# Nodes" "Distance"`

ty in advance

**Comment by WillyWinkel** [comment]
fixed it by setting `yLim <- range(c(0,yData+e)) + c(0, deltaY)` .... stupid me

**Comment by thillux** [comment]
included your confidence script in the repo, thanks :)
